version: '3.8'
services:
  db:
    container_name: blog-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_db
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/blog_db?schema=public
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
